# Generated by Django 5.2.8 on 2025-11-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Pacote')),
                ('descricao', models.TextField(verbose_name='Descrição Completa')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('data_viagem', models.DateField(verbose_name='Data da Viagem')),
                ('imagem', models.ImageField(upload_to='pacotes/', verbose_name='Foto do Destino')),
                ('categoria', models.CharField(choices=[('NAC', 'Nacional'), ('INT', 'Internacional')], default='NAC', max_length=3)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Pacotes de Viagem',
            },
        ),
    ]
